apiVersion: v1
kind: Secret
metadata:
  name: chm-secret
  namespace: chm
type: Opaque
stringData:
  DATABASE_URL: postgresql://postgres:secret@db:5432/monitor
  POSTGRES_PASSWORD: secret
  CORS_ORIGINS: "*"
